name: Publish Crate

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"

      - uses: Swatinem/rust-cache@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Publish
      - name: Publish
        run: |
          cargo publish -p knf-rs-sys :: |
          cargo publish -p knf-rs :: |
          cargo publish -p pyannote-rs
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
